Description: Create the function that processes requests from the Amazon Alexa service.
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Mappings:
    Variables:
        AlexaSkillKit:
            Id: amzn1.ask.skill.xxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

Outputs:
  LambdaFunctionArn:
    Description: Alexa Skill ARN
    Value:
      Fn::GetAtt:
      - SumoLogicAlexaSkill
      - Arn

Resources:
  SumoLogicAlexaSkill:
    Type: AWS::Serverless::Function
    Properties:
      Layers:
      - arn:aws:lambda:us-east-1:173334852312:layer:ask-sdk-for-python-36:1
      MemorySize: 256
      Handler: lambda_function.lambda_handler
      Timeout: 900
      CodeUri:
        Bucket: awsserverlessrepo-changesets-plntc6bfnfj
        Key: AIDAIFSYKQFCV6O2ZUR4M-61fe05d1-8872-4326-be91-eaec92a186dc
      Runtime: python3.6
      # Events:
      #   AlexaTrigger:
      #     Type: AlexaSkill
      FunctionName:
        Fn::Join:
        - '-'
        - - Ref: SumoLogicAlexaSkill
          - Fn::Select:
            - 4
            - Fn::Split:
              - '-'
              - Fn::Select:
                - 2
                - Fn::Split:
                  - /
                  - Ref: AWS::StackId

  AlexaSkillPermission:
        Type: AWS::Lambda::Permission
        DependsOn: SumoLogicAlexaSkill
        Properties:
            Action: lambda:InvokeFunction
            EventSourceToken: !FindInMap
                - Variables
                - AlexaSkillKit
                - Id
            FunctionName: !GetAtt SumoLogicAlexaSkill.Arn
            Principal: alexa-appkit.amazon.com

